config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show] do
    resources :posts do
      resources :comments
      resources :likes, only: %i[new create]
    end
  end
  # Defines the root path route ("/")
  post '/likes/new', to: 'likes#create'
  get '/posts', to: 'posts#all_posts'
  get '/about_us', to: 'about_us#index'
  root 'users#index'

  namespace :api do
    resources :users do
      resources :posts do
        resources :comments
      end
    end
  end

  namespace :api do
    resources :authentications, only: :create
  end
end

app/views/shared/_comments.html.erb
<div class = 'list-group p-1 mt-1 comment-list'>

<% @comments.each do |comment|%>
  <div class='bg-light p-1 d-flex justify-content-between'>
  <span> <span class='fw-bold '>@<%=comment.user.name.strip%>:</span> <%=comment.text%></span>
    <% if can? :destory, comment%>
        <%= button_to "🗑️", user_post_comment_path(comment.user_id, comment.post_id, comment.id), method: :delete , class: ' btn btn-danger'%>
    <% end %>
  </div>
<%end%>
</div>

app/views/shared/_postlist.html.erb
<%if !user_signed_in? %>
   <h2 class='alert alert-warning text-center'> <%=link_to 'log in' , new_user_session_path %> or <%=link_to 'sign up', new_user_registration_path %> to interact </h2>
<%end%>
<ul class='list-group mt-3'>
  <% @posts.each do |post| %>
    <% @comments = post.comments%>
    <% @time_name = post.get_time_ago[:time_name]; @post_time_ago = post.get_time_ago[:post_time_ago] %>
    <li class='list-group-item '>
    <div class='post-title-text'>
      <span class='post-time'>This post was published 
      <% unless @time_name == 'just now' %> <%= @post_time_ago.floor%> <%end%>
       <%=@time_name%>  </span>
      <h4>Title: <%= post.title %> </h4>
      <p class='p-2 '> <%= post.text%> </p>
    </div>
    <div>
      <span>comments: <%= post.comments.length %></span>
      <span class='ml-2'>likes: <%= post.likesCounter%></span>
    </div>
        
    <% unless @comments.empty? %>
      <% @comments = @comments.limit(4) %>
      <%= render :partial => "shared/comments", :comments => :comments %>
      <br>
      <%= link_to 'see all comment ...', user_post_comments_path(@user.id, post.id), class: '' %>
    <% end %>
    <br>
    <div class = 'btn-group align-text-center w-100'>
      <%= link_to 'see post', user_post_path(@user,post), class:'btn btn-outline-dark ' %>
      <%if user_signed_in? %>
        <% if post.already_liked?(current_user) %>
          <%= form_with model: @like, class: 'btn btn-danger', url: likes_new_path do |form| %>
            <%= form.hidden_field :post_id, value: post.id %>
            <%= form.submit "UnLike Post",class:'btn btn-danger w-100' %>
          <% end %>
        <% else %>
          <%= form_with model: @like, class: 'btn btn-danger', url: likes_new_path do |form| %>
            <%= form.hidden_field :post_id, value: post.id %>
            <%= form.submit "Like Post",class:'btn btn-danger w-100' %>
          <% end %>
        <% end %>
        
        <%= link_to 'comment', new_user_post_comment_path(@user,post), class:'btn btn-outline-primary' %>
      <%end%>
    </div>
    <% end %>
  </li>
</ul>