config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show] do
    resources :posts do
      resources :comments
      resources :likes, only: %i[new create]
    end
  end
  # Defines the root path route ("/")
  post '/likes/new', to: 'likes#create'
  get '/posts', to: 'posts#all_posts'
  get '/about_us', to: 'about_us#index'
  root 'users#index'

  namespace :api do
    resources :users do
      resources :posts do
        resources :comments
      end
    end
  end

  namespace :api do
    resources :authentications, only: :create
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded mt-1 mb-2">
  <div class="container-fluid">
  <% if user_signed_in? && (request.path.to_s.include? "new") %>
    <%= link_to '', :back, class:'fa fa-arrow-left go-back' , id: 'go-back'%>
  <%end%>
  <%= link_to 'users', users_path, class: 'navbar-brand', id: 'navbar-brand' %>
    <button class="navbar-toggler border-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav align-items-center">
        <% if user_signed_in? %>
          
          <li class="nav-item">  <%= link_to 'create a new post', new_user_post_path(current_user), class: 'nav-link ' %> </li>
          <li class="nav-item">  <%= link_to 'My posts', user_posts_path(current_user), class: 'nav-link' %> </li>
          <li class="nav-item"> <%= link_to 'see my profile', user_path(current_user), class: 'nav-link' %> </li>
          <li class="nav-item">  <%= button_to 'sign out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger' %> </li>
        
        <% else %>
        <li class="nav-item"><%= link_to 'sign up', new_user_registration_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'sign in', new_user_session_path, class: 'nav-link' %></li>
        <% end %>
        <li class="nav-item"> <%= link_to 'See all posts', posts_url, class: 'nav-link' %> </li>
        <li class="nav-item"> <%= link_to 'about us', '/about_us', class: 'nav-link' %> </li>
      </ul>
    </div>
  </div>
  <script>
  (function() {
    let navBrand = document.getElementById('navbar-brand');
    let goBack = document.getElementById('go-back');
    if (goBack) { navBrand.style.marginLeft = '2rem'; }
    })();
  </script>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anek+Telugu:wght@200;300&family=Roboto:wght@300&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true, type: 'module' %>  
  </head>

  <body class=''>
    <div class= 'container bg-light mb-2 p-1'>
      <%= render 'layouts/navbar' %>
      <% if alert %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong><%= alert%></strong> 
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      <%end%>
      <% if notice %>
      <p class= 'alert alert-success'><%= notice%> </p>
      <script>
     // this function auto removes the notification after 2 seconds
        setTimeout (function () {
        let alertElement = document.querySelector('.alert')
        alertElement.remove()
        }, 2000);
      </script>
      <%end %>
      <%= yield %>
      
    </div>
    
</html>